name: selk_warehouse_app
description: "Sistema de Gestión de Almacén SELK para PDAs"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3

  # Network
  http: ^1.1.0
  dio: ^5.3.2
  connectivity_plus: ^5.0.1

  # Storage
  sqflite: ^2.3.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2

  # Dependency Injection
  get_it: ^7.6.4

  # Utils
  equatable: ^2.0.5
  dartz: ^0.10.1
  logger: ^2.0.2+1
  device_info_plus: ^9.1.0
  package_info_plus: ^4.2.0

  # Date/Time
  intl: ^0.18.1

  # Security
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
